### PR TITLE
feat(Add): `npm` icon

### PR DESCRIPTION
**Pull request by bdbch**
Added the npm icon requested in #75.

image

### CODE REVIEW

**Comment by colebemis** [comment]
Thanks for opening these pulls, @bdbch! I'm going to hold off merging anything into the project until I finish up the design guidelines and contribution instructions. Stay tuned 🙂

**Comment by bdbch** [comment]
Aye aye!

Any informations on when you'll add contribution guidelines and/or documentations?

**Comment by colebemis** [comment]
They're coming. I've been pretty busy with finals and work so I haven't had time to work on them, but once summer break starts, I'll have more free time.

**Comment by mittalyashu** [comment]
@bdbch Can you update the icon by following the Feather icon guidelines on #171

**Pull request closed without merging**
