### PR TITLE
Add contact icon

### LINKED ISSUE #861: Icon Request: Contact
# Icon Request

* Icon name: contact / contact-card / rolodex
* Use case: Address book, contacts, contact card, (sales) leads, profile details, etc. Any kind of application that has a CRM type use case.
* Screenshots of similar icons...

From Google Material icon library:
Screen Shot 2020-03-28 at 8 35 23 AM
Screen Shot 2020-03-28 at 8 35 30 AM
Screen Shot 2020-03-28 at 8 35 34 AM

Random Icon I found online that looks more like an actual rolodex card and communicates the concept more clearly in my opinion:
Screen Shot 2020-03-28 at 8 36 04 AM

Similar icons that don't quite work:

* Best possible alternative is the book icon. It's more generic but it_could_ get the point across, though it's more ambiguous.
* Phone icon could work, but then you're overloading a specific piece of information about a contact so you can't really use the phone icon for `tel:` links or phone form fields.
* User icon could work, but then you're overloading your user icon, which has numerous other possible uses. Users and contacts are not always the same

### PR DESCRIPTION
**Pull request by lscheibel**
Screenshot:

image

closes #861

### CODE REVIEW

**Comment by lscheibel** [comment]
Should the `<circle>` and `<rect>` elements be turned into paths or what exactly do you mean?

**Comment by tmcgann** [comment]
@lscheibel I'm not sure how to create a compound path in your tool of choice, but an article like this might help you understand what, why, and how: https://css-tricks.com/lodge/svg/25-manually-optimizing-svg-illustrator/

**Comment by locness3** [comment]
> Should the `<circle>` and `<rect>` elements be turned into paths or what exactly do you mean?

No, I mean using the `Join Paths` option (or otherwise called depending on your software)

**Comment by lscheibel** [comment]
Hey, sorry but I'm not sure what paths to join. I got this one now and I don't see what paths would need merging. Can you guide me in the right direction?

```
<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24"
  width="24"
  height="24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M19 22H5c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2h14c1.1 0 2 .9 2 2v14c0 1.1-.9 2-2 2z" />
  <line x1="16" y1="2" x2="16" y2="4" />
  <line x1="8" y1="2" x2="8" y2="4" />
  <circle cx="12" cy="11" r="3" />
  <path d="M17 18.5c-1.4-1-3.1-1.5-5-1.5s-3.6.6-5 1.5" />
</svg>
```

**Comment by locness3** [comment]
Hmmm, in fact I think it's not necessary

**Comment by tmcgann** [comment]
What's the next step to get this merged now that it's been approved and passed checks?

**Comment by jletey** [comment]
@lscheibel Just waiting on @colebemis.

**Comment by ericfennis** [comment]
@lscheibel if like to contribute, maybe you want to joins us at https://github.com/featherity/featherity and open this PR there 😁

**Comment by jgonera** [comment]
Doesn't it look a bit like a sad square-faced cyclops? :)

**Comment by tmcgann** [comment]
@jgonera Sad square-faced cyclops robot. 😆

**Comment by locness3** [comment]
FYI, Ischeibel has contribtued this icon to @lucide-icons.

**Pull request closed without merging**
