### PR TITLE
feat: add icon VSCO

### PR DESCRIPTION
**Pull request by asci**
fixes https://github.com/feathericons/feather/issues/715

### CODE REVIEW

**Comment by asci** [comment]
anything else required for merge?

**Comment by johnletey** [comment]
@colebemis?

**Comment by asci** [comment]
closing due to no response from maintainers

**Comment by johnletey** [comment]
@asci I'd keep this open, I have pull requests open from June. As soon as @colebemis has time, he'll make sure to review your icon!

**Comment by locness3** [comment]
@asci see #763

**Pull request closed without merging**
