### PR TITLE
Add icon Open Maill

### PR DESCRIPTION
**Pull request by JoaoPedroMoraes**
Addition of the open mail icon as requested in issue #563. The icon was created based on the issue #171 guidelines.

### CODE REVIEW

**Comment by locness3** [comment]
BTW you could just modify the mail icon svg for more consistency.

**Comment by JoaoPedroMoraes** [comment]
The modifications were made to the pull request as you requested @locness3

**Comment by JoaoPedroMoraes** [comment]
Corrections made as order :+1:

**Comment by mittalyashu** [comment]
Not sure, but there should be a tiny bit of spacing.

image

**Comment by locness3** [comment]
Why did you close @JoaoPedroMoraes

**Pull request closed without merging**
