### PR TITLE
Add new minimize and maximize icons

### LINKED ISSUE #436: More obvious full screen & Minimise screen

### PR DESCRIPTION
**Pull request by johnletey**
Closes #436

### CODE REVIEW

**Comment by johnletey** [comment]
Sorry ... created a branch out of a different branch instead of master ... opening a new PR @locness3!

**Comment by locness3** [comment]
Why are you telling me lol? I'm not a maintainer, manager or anything like this lol

**Comment by johnletey** [comment]
lol I thought you were a maintainer @locness3 ... well then sorry @colebemis!

**Comment by locness3** [comment]
> lol I thought you were a maintainer @locness3 ... well then sorry @colebemis!

lol

**Pull request closed without merging**
