### PR TITLE
feat: Added bitbucket icon

### PR DESCRIPTION
**Pull request by bdbch**
Added bitbucket icon as requested in #479

Preview:
image

### CODE REVIEW

**Comment by mittalyashu** [comment]
I don't know, if it aligns with BitBucket brand guidelines, we need to ask their design team for the same.

**Comment by mittalyashu** [comment]
| Icon | Suggestion |
| --- | --- |
| Figma_ZcBPs9EDPx | Figma_mQvD66Mmp8 |

@locness3, what do you think?

**Comment by locness3** [comment]
🤷‍♂

**Comment by locness3** [comment]
idk

**Comment by colebemis** [comment]
Thanks for opening this PR, @bdbch! But I'm going to close this because we've decided to stop adding logo icons to Feather (see #763 for more details).

**Pull request closed without merging**
