### PR TITLE
Add utensils icon.

### PR DESCRIPTION
**Pull request by lukashambsch**
Utensils icon for https://github.com/feathericons/feather/issues/552.

### CODE REVIEW

**Comment by johnletey** [comment]
@lukashambsch Make sure to run `npm run build`!

**Comment by lukashambsch** [comment]
> @lukashambsch Make sure to run `npm run build`! It formats the icon

Looks like it doesn't like something about the format. I've formatted it manually.

**Comment by lukashambsch** [comment]
> Please clean up your svg like other icons. And please make sure you follow #171 .

@locness3 Can you please be more specific on the changes you'd like to see?

I'm not a designer & I hired someone to create the icon. They say they followed #171. With some more specific feedback, I can get them to update the icon.

Thanks!

**Comment by locness3** [comment]
> > Please clean up your svg like other icons. And please make sure you follow #171 .
> 
> @locness3 Can you please be more specific on the changes you'd like to see?

I would like that you clean the svg so it is like the other icons. You can look at them to see what I mean.

**Comment by lukashambsch** [comment]
> > > Please clean up your svg like other icons. And please make sure you follow #171 .
> > 
> > 
> > @locness3 Can you please be more specific on the changes you'd like to see?
> 
> I would like that you clean the svg so it is like the other icons. You can look at them to see what I mean.

@locness3 Thanks! Is it better now?

**Comment by johnletey** [comment]
@lukashambsch Remove [this](https://github.com/feathericons/feather/pull/629/files#diff-430a07cf4be69c00db333928596c0314R2) line ... it is not necessary and no other icons have it

**Comment by lukashambsch** [comment]
@johnletey @locness3 I removed it.

**Comment by lukashambsch** [comment]
@locness3 Is there anything else I can do to get this merged?

**Comment by locness3** [comment]
> @locness3 Is there anything else I can do to get this merged?

Waiting for @colebemis's approval

**Comment by mittalyashu** [comment]
Got an idea, @lukashambsch can you split the icon into 3 different icons

1. Spoon
2. Fork
3. Spoon and fork

**Comment by mittalyashu** [comment]
2px spacing around the icon

| Icon | Suggestion |
| --- | --- |
| Figma_cwlxbFMRng | Figma_DLHKHZU0yV |

**Pull request closed without merging**
