### PR TITLE
Dl reply all

### PR DESCRIPTION
**Pull request by dustinlocke**
Reviewed spacing guidelines and updated reply-all icon to have proper 2px between strokes.

### CODE REVIEW

**Comment by locness3** [comment]
Why haven't you pushed to your fisrt pull request @dustinlocke ?

**Comment by locness3** [comment]
Or at least close it @dustinlocke

**Comment by dustinlocke** [comment]
Sorry I'm a bit of a Git newcomer. Let me close this one and update that one. Feels like the cleanest way.

**Comment by locness3** [comment]
> Sorry I'm a bit of a Git newcomer. Let me close this one and update that one. Feels like the cleanest way.

GitHub learning lab has great ressources to learn git and github. @dustinlocke

**Pull request closed without merging**
