### PR TITLE
Feature: add bed & building icons

### LINKED ISSUE #68: Icon request: bed
Hi, thanks for the great set of icons!

How about some icons for describing rooms within a house

**Icon name:** bed
**Use case:** Many real estate agents make use of such icons when advertising properties.

I've included an example below.

image

### LINKED ISSUE #391: Icon Request: Bed Icon
## Bed

This would be useful for real estate and hospitality

hotel-bed-2.pdf

### PR DESCRIPTION
**Pull request by pkrawc**
Closes #68 & closes #391

### CODE REVIEW

**Comment by locness3** [comment]
You should say "Closes #68 and closes #391", because GitHub takes only into account the first one after "closes"

**Comment by pkrawc** [comment]
Strange. I've updated the icon. I'm unsure why it was so convoluted before.

Good catch @locness3 .

**Comment by locness3** [comment]
> You should say "Closes #68 and closes #391", because GitHub takes only into account the first one after "closes"

Please do that as I already said.

**Comment by mittalyashu** [comment]
Should the PR include a `package-lock.json` file?

The bed doesn't look like bed

| Icon | Suggestion |
| --- | --- |
| Figma_avnpvQYUAL | Figma_ZfxKW6VAnp |

**Comment by locness3** [comment]
idk tbh

**Comment by pkrawc** [comment]
bed

Split the difference?

**Comment by locness3** [comment]
Note that these icons have been added to @lucide-icons, a community fork :

https://lucide.dev/icon/building?search=building
https://lucide.dev/icon/bed?search=bed

**Pull request closed without merging**
