### PR TITLE
Added figma link to ##Related Projects

### PR DESCRIPTION
**Pull request by ashygee**

### CODE REVIEW

**Comment by colebemis** [comment]
Also, should we have a "draft" figma file to play around with new icon designs and a "public" file that has the finalized icons that are also published on npm?

**Comment by ashygee** [comment]
Oh I like that! I wasn't sure since the Sketch library was referenced under `Related Projects`. Are we thinking of making this an "Official item" @colebemis? If so I can write up the docs to the README.

**Comment by colebemis** [comment]
Yeah, let's integrate it into the docs 👍 The sketch library is only in `Related Projects` because it has it's own repo: https://github.com/feathericons/sketch-feather

**Comment by ashygee** [comment]
Closing this pr since #518 addresses this.

**Pull request closed without merging**
