### PR TITLE
feat: Add `divide` icons

### LINKED ISSUE #263: Icon Request: divide
Icon name: divide
Use case: in calculator applications, math games, etc.

### PR DESCRIPTION
**Pull request by csandman**
Added 3 division icons (also knows as an obelus).  One by itself, one with a circle around it, and one with a square around it.  These are meant to compliment the plus, minus, and x icons and fill out the set of math icons.

Screenshot 2019-04-01 21 13 06

The shapes are composed the same way as they are in the other math icons, using 1px lines for the points.

Closes #263

### CODE REVIEW

**Comment by colebemis** [comment]
@csandman These look great! Thanks for opening a PR 🎉 

My only feedback is that the dots on the `divide` icon might be a little small relative to the rest of the icon: 

image

Could you try a version that uses a larger circle similar to the `percent` icon? 

image

**Comment by csandman** [comment]
divide
@colebemis Sorry I saw your comment so late!  I gave it a shot, is this what you were thinking of?

The main reason I avoided this is because I felt that the circles were a bit too large but its up to you.

**Comment by mittalyashu** [comment]
@csandman If you zoom out the divide icon looks perfect with bigger dots.

**Comment by ElForastero** [comment]
Yeah, it looks a little bit thin related to other icons.

But I still love it 😉

image

**Comment by csandman** [comment]
I know this is rather old, but I never pushed my change with the change requested by @colebemis 

Anyway, now I have so feel free to merge if you like the change!

Here is what all 3 icons look like in context of the other icons:
Frame 1

**Review by FirstLast94397 — APPROVED** [review]

**Pull request merged**
