### PR TITLE
feat: New file type, unlink and presentation icons

### PR DESCRIPTION
**Pull request by ThomasKuhlmann**
Contains 21 new icons

image

### CODE REVIEW

**Comment by locness3** [comment]
Why have you closed @ThomasKuhlmann ?

**Comment by ThomasKuhlmann** [comment]
@locness3 Sorry, that was the first time I ever uploaded anything on github... and something had gone wrong with my commit. I added another pull request which contains the correct files (wasn't sure how/if I could change this wrong one...)

**Comment by locness3** [comment]
You could have change it, just by comitting to your branch

**Comment by ThomasKuhlmann** [comment]
Cheers, I'll remember that for the next time!

**Pull request closed without merging**
