### PR TITLE
Created an icon for X (the new Twitter logo)

### PR DESCRIPTION
**Pull request by Exetric**
I made this for my personal website and thought I might contribute it to the project because I made it to be the same style.

### CODE REVIEW

**Comment by zarazinsfuss** [comment]
This would implement [Issue #1207](https://github.com/feathericons/feather/issues/1207):
Icon Request: Twitter ⇒ 𝕏

**Review by zarazinsfuss — COMMENTED** [review]
Well done. Looks in line with the feather aesthetic.

**Comment by terrablue** [comment]
Hi, is this icon not smaller when compared to the others?

x-icon

**Comment by Exetric** [comment]
> Hi, is this icon not smaller when compared to the others?
> 
> x-icon

Thanks for showing me this I didn't notice, I just updated the icon to fix this so it should be good

**Comment by terrablue** [comment]
Works for me, thanks.

**Comment by ryanfurrer** [comment]
Bumping this for PR review - would love to use this!

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated: #763 

I'm sorry to say that this PR will almost certainly never ever get merged.

**Comment by ryanfurrer** [comment]
> Brand icons are deprecated: #763
> 
> I'm sorry to say that this PR will almost certainly never ever get merged.

Damn, that's a bummer. 
Thanks for letting me know.

**Review by NotReeceHarris — APPROVED** [review]

**Comment by NicolaCocozza** [comment]
Any news?

**Comment by yurist38** [comment]
Would be great to have the new Twitter icon included. Please give this one the green light!

**Comment by adammoisa** [comment]
+1

**Comment by 5d5f8a0** [comment]
X

**Pull request closed without merging**
