### PR TITLE
added sketch library

### PR DESCRIPTION
**Pull request by thatgibbyguy**
I've just created a library in sketch that allows you to use feather icons as a symbol. [Examples of its usage are available here](https://johngibby.com/blog/Feather_Icons_as_a_Sketch_Library).

### CODE REVIEW

**Comment by colebemis** [comment]
This is awesome! 🎉  Thanks for taking to the time to make this. Do you have a plan for keeping the sketch file up-to-date with the SVGs? Is there a way to automatically generate this file so it doesn't involve so much manual work?

**Comment by thatgibbyguy** [comment]
I've been looking at ways to automate that, but so far have come up empty. My strategy was just to track merges in this repo and then add. I also have plans to add major color libraries (like material's color library, etc) into it. So for now, I think it has to be manually kept up.

Of course, icons could also been designed inside of this file.

**Comment by colebemis** [comment]
Have you thought about teaming up with @odmln to maintain https://github.com/odmln/sketch-feather? If @odmln is up for it, I'd love to transfer that repo to the [feathericons](https://github.com/feathericons)  GitHub organization and add you two as members.

**Comment by thewinger** [comment]
I've been using odmln's feather library for a while and works pretty well and have a good all round set of colours.

Also, maybe this plugin is useful to speed up the SVG → Sketch process 
https://github.com/AMoreaux/Sketch-Icons

**Comment by odmln** [comment]
I'm almost finished updating the the file with more icons, plan on pushing out an update this week!

**Comment by thatgibbyguy** [comment]
@odmln I've already got the entire current set in the file I made. I actually didn't know about your sketch library before this, so what would it take to get us to combine our files (decrease our work) and get it added to this repo?

@colebemis do you have any ideas for this? my primary goals are making sure that their is an "official" sketch library and that it is easy to find (ie, is in the official repo and/or on the url).

**Comment by thatgibbyguy** [comment]
@thewinger that's awesome. looks like something we could write a script that checks on release hooks and imports each icon at that time to regen the sketch file. something to look into.

**Comment by odmln** [comment]
@thatgibbyguy I got all the new icons loaded into my sketch doc today, will push and make a new release tomorrow. Thinking moving forward though we can team up and add even more design resources to the repo? Figma, Adobe XD, and Invision Studio when it's released. That way we cover all platforms and can reach more designers.

I designed my doc to have each icon at 24x24px since thats pretty standard. I have material colors in my doc currently but like the idea of having more color options available. Maybe we can create a separate sketch doc with preset color schemes — that way it's not mixed into the same doc as the icons. 

@colebemis if that sounds good I'd love to transfer the repo into the feathericons github org. Also, do you have a Slack team for Feather or do you like Spectrum better? We can all talk more about these design plans on one of those platforms instead? Let me know!

**Comment by odmln** [comment]
@colebemis @thatgibbyguy just pushed to my repo, new icons have been added.

**Comment by colebemis** [comment]
Okay, how about we transfer https://github.com/odmln/sketch-feather to [feathericons](https://github.com/feathericons) and I'll make both of you as members of the organization. Once that's done, we can add a "Sketch" subsection to the Usage section in the README that links to the `sketch-feather` repo.  Sound good @thatgibbyguy @odmln?

Regarding automation, https://github.com/AMoreaux/Sketch-Icons seems really promising. That's definitely something we should try. Thanks for the suggestion, @thewinger!

Let's use the [Spectrum community](https://spectrum.chat/feather) for further planning.

**Comment by thatgibbyguy** [comment]
@colebemis sounds good to me. @odmln also sounds good to me. i was planning on adding material, but since you did that my next suggestion was to add the predix colors (https://www.predix-ui.com/#/css/visual/px-colors-design) because selfishly, I work at GE so ... 
 Also, would love to help for those other platforms. 

If it helps for me to write the readme, or whatever, let me know.

**Comment by colebemis** [comment]
@thatgibbyguy @odmln Just invited you guys to join the feathericons organization 🎉  

@odmln Feel free to transfer `sketch-feather` whenever you have time 👍

**Comment by odmln** [comment]
@colebemis `sketch-feather` has been transferred!

**Comment by thewinger** [comment]
Will it be possible to PR icons to the Sketch file directly and move that to SVG or only from SVG → Sketch?

**Comment by thatgibbyguy** [comment]
@thewinger I am very curious about this as well, will look into it but I think the best way right now would be to watch the repo for new releases and add the icons at that point, unless we asked the contributors of icons to make both the svg and update the sketch file at once (I think that's a big ask).

**Comment by ahuk** [comment]
@thatgibbyguy having that as a library might be even better than having an icon font. Although browsing a font in Font Book is simpler than open the library every time.

**Comment by thewinger** [comment]
Yeah, I also think is a big ask.
I thought about it because the few icons I have made I have with Sketch, but most people that want to collaborate will use Illustrator for example.

**Comment by colebemis** [comment]
>  I think the best way right now would be to watch the repo for new releases and add the icons at that point

I agree. I think it's best if the `feather` repo remains the single source of truth and we can make `sketch-feather` a reflection of the main repo.

**Comment by colebemis** [comment]
I'm going to go ahead and close this pull. We can move further discussion to [sketch-feather](https://github.com/feathericons/sketch-feather) or [Spectrum](https://spectrum.chat/feather).

**Pull request closed without merging**
