### PR TITLE
feat: Add SoundCloud icon

### PR DESCRIPTION
**Pull request by shawnwwwww**
followed guideline from #171

### CODE REVIEW

**Comment by moechaieb** [comment]
LGTM. I'll let @locness3 approve though :)

**Comment by shawnwwwww** [comment]
> LGTM. I'll let @locness3 approve though :)

idk i need to clean the svg code as well so it might takes some time

**Comment by shawnwwwww** [comment]
> Remove , <title>, , and other not useful tags. remove ids. Just keep the necessary svg. You can see other icons's svg code to get an idea of how it should be.

i've compared a few official icons and cleaned it up :)

**Comment by colebemis** [comment]
> Now please remove line breaks for svg tag

@locness3 Line breaks are okay. The `build` script actually uses prettier to format the SVGs 😄 

@shawnwwwww It looks like there might be a viewBox issue. This is how GitHub renders the SVG: 

image

**Comment by locness3** [comment]
> @locness3 Line breaks are okay. The `build` script actually uses prettier to format the SVGs 😄
Oh ok sorry

**Comment by colebemis** [comment]
@locness3 No need to apologize 😄 I really appreciate all your help!

**Comment by mittalyashu** [comment]
@shawnwwwww Can you fix the issue?

Change the PR title to `Add SoundCloud icon`

**Comment by locness3** [comment]
> Change the PR title to `Add SoundCloud icon`

Or feat: Add SoundCloud icon

**Comment by shawnwwwww** [comment]
> > Change the PR title to `Add SoundCloud icon`
> 
> Or `feat: Add SoundCloud icon`

changed!

**Comment by shawnwwwww** [comment]
> @shawnwwwww Can you fix the issue?
> 
> Change the PR title to `Add SoundCloud icon`

changed to feat: Add SoundCloud icon

**Comment by mittalyashu** [comment]
While previewing the icon it is showing.

image

🤔

**Comment by johnletey** [comment]
@shawnwwwww Change the icon to this so that the icon completely fits in the 24x24px grid

Shot 2019-07-22 at 12 35 13

```svg
<svg
  width="24"
  height="24"
  viewBox="0 0 24 24"
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path
    clip-rule="evenodd"
    d="M13 17.236h7.3C22.096 17 23 16.084 23 14.488c0-1.596-.904-2.457-2.7-2.583h-.338c0-1.974-.866-3.409-2.598-4.305-1.732-.897-2.716-.788-4.364.327v9.31z"
  />
  <path d="M10 8.766v8.47" />
  <path d="M7 10.178v7.058" />
  <path d="M4 12.295v4.941" />
  <path d="M1 14.354v2.47" />
</svg>
```

**Comment by locness3** [comment]
I think you should keep some spacing @johnletey

**Comment by johnletey** [comment]
@locness3 There is a 1px space between everything

**Comment by locness3** [comment]
Between the borders of the icon

**Comment by johnletey** [comment]
@locness3 I've added 1px between the borders of the icon

Shot 2019-07-22 at 16 35 00

@shawnwwwww Use this:

```svg
<svg
  width="24"
  height="24"
  viewBox="0 0 24 24"
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M8 8.766v8.47" />
  <path d="M5 10.178v7.058" />
  <path d="M2 12.295v4.941" />
  <path d="M11 16.973l7.175.027h.668C20.924 17 22 15.539 22 14.084c0-1.454-1.119-2.741-3.157-2.741h-.668V9.76c0-1.191-.58-2.935-2.625-3.56-2.044-.627-4.55.248-4.55 2.187v8.585z" />
</svg>
```

**Comment by locness3** [comment]
@shawnwwwww Could you update your icon ?

**Comment by colebemis** [comment]
Thanks for opening this PR, @shawnwwwww! But I'm going to close this because we've decided to stop adding logo icons to Feather (see #763 for more details).

**Pull request closed without merging**
