### PR TITLE
New file type, unlink and presentation icons

### PR DESCRIPTION
**Pull request by ThomasKuhlmann**
image

### CODE REVIEW

**Comment by mittalyashu** [comment]
@ThomasKuhlmann, please update the icons by following the Feather guidelines from #171

**Comment by ThomasKuhlmann** [comment]
@locness3 @mittalyashu happy to make some changes if I can - but I had a look at the guidelines and the other icons again, andI just can't figure out what you want me to change. Can you be a bit more specific about what is wrong? Do I have to run every single icon through e.g. https://jakearchibald.github.io/svgomg/ ? or is there something wrong with the icons themselves or the way I added them?

**Comment by locness3** [comment]
@ThomasKuhlmann Please read my review.

**Comment by locness3** [comment]
🤦‍♂

**Comment by locness3** [comment]
I'm referring to [this](https://github.com/feathericons/feather/pull/596#pullrequestreview-252391606) comment. Why did your review to post your comment BTW ?

**Comment by mittalyashu** [comment]
@ThomasKuhlmann, you can watch this video _(I have created)_ https://www.youtube.com/watch?v=5fMheOCcVIw

**Comment by ThomasKuhlmann** [comment]
@mittalyashu you, sir, are my hero! Thanks for the effort!
I don't think I'll be able to make all the changes (I paid a designer to create those icons), but I can definitely structure the SVG the way you suggested. And if it turns out that one of the file icon series is not up to scratch because of its padding, I can just remove it from the PR; I guess two variations per file type is enough anyway

**Comment by ThomasKuhlmann** [comment]
@locness3 because I looked at your review and then left a comment there... 🙄 The good thing with first timers like me is that we do stupid mistakes with high entertainment value 😁

**Comment by MarcelloTheArcane** [comment]
Look what happens when the icon is small (which is the default):

image

These icons are outlined, which is not compliant with Feather Icons.

**Pull request closed without merging**
