### PR TITLE
Feature: added calculator icon

### LINKED ISSUE #462: Icon Request: Calculator
## Icon Request

* Icon name: Calculator
* Use case: To be used for in-app calculations, such as converting currencies
* Screenshots of similar icons: 
high-contrast-accessories-calculator svg

### PR DESCRIPTION
**Pull request by btn0s**
Added calculator icon to close #462

### CODE REVIEW

**Comment by btn0s** [comment]
Yeah looking at it now in the preview it’s not the same as when I preview it in the browser. Also the grouping came from SVGOMG I guess, I’ll get the original from Figma and see what’s the difference.

Will resubmit in the morning.

**Comment by ahtohbi4** [comment]
Maybe it should be looks like this:

Снимок экрана 2019-07-01 в 12 13 46

Code:

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <rect x="6" y="3" width="12" height="18" rx="2" />
  <path d="M9 18V18" />
  <path d="M9 15V15" />
  <path d="M9 12V12" />
  <path d="M12 18V18" />
  <path d="M12 15V15" />
  <path d="M12 12V12" />
  <path d="M15 18V18" />
  <path d="M15 15V15" />
  <path d="M15 12V12" />
</svg>
```

**Comment by johnletey** [comment]
@ahtohbi4 I really like the icon that you designed ... one note, maybe add a "screen" to the icon?

**Comment by ahtohbi4** [comment]
@johnletey let's try :)

Снимок экрана 2019-07-01 в 15 22 01

But I had to do this version of calculator wider.

**Comment by johnletey** [comment]
Although it is a wider icon @ahtohbi4 ... I love it with the screen!

**Comment by locness3** [comment]
> @johnletey let's try :)
> 
> Снимок экрана 2019-07-01 в 15 22 01
> 
> But I had to do this version of calculator wider.

I think it looks to detailed for small sizes. you could you try removing some buttons.

**Comment by ahtohbi4** [comment]
Has been tried to reduce the details:

Снимок экрана 2019-07-01 в 23 23 15

**Comment by locness3** [comment]
Why not ? I think it looks weird with the keys not being circles though. Maybe have only four keys, and make them circles ?

**Comment by ahtohbi4** [comment]
Let's try 🙂

Снимок экрана 2019-07-02 в 11 03 50

**Comment by locness3** [comment]
That's great now!

**Comment by ahtohbi4** [comment]
@btn0s you can take the code if you wish:

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <rect x="5" y="2" width="14" height="20" rx="2" />
  <rect x="9" y="6" width="6" height="4" />
  <path d="M10 14V14M14 14V14M10 18V18M14 18V18z" />
</svg>
```

**Comment by btn0s** [comment]
I liked the non-circle buttons more imo, iOS is the only calc I know of with circle buttons -- most have rounded squares. That said if everyone else is happy with this I'll update the code.

**Comment by btn0s** [comment]
> Let's try 🙂
> 
> Снимок экрана 2019-07-02 в 11 03 50

@locness3 the more I look at this last iteration the more it looks like a 90's cellphone. Any chance of compromise and go with the one above?

**Comment by locness3** [comment]
> @locness3 the more I look at this last iteration the more it looks like a 90's cellphone.

Oh

**Comment by btn0s** [comment]
> Has been tried to reduce the details:
> 
> Снимок экрана 2019-07-01 в 23 23 15

Can I get the code for this one? This is the one I'd like to submit.

**Comment by locness3** [comment]
@btn0s This one seems too cluttered. Maybe doing only four buttons.

**Comment by btn0s** [comment]
As long as it keeps the width, we don't want it to look like a cellphone.

**Comment by locness3** [comment]
The more simpler the more Fetaher-ish though. @colebemis ?

**Comment by mittalyashu** [comment]
1. This https://github.com/feathericons/feather/pull/612#issuecomment-507243151 does look like a calculator.
2. This https://github.com/feathericons/feather/pull/612#issuecomment-507413384 looks like a game with a small screen and a bigger button.
  image
3. This https://github.com/feathericons/feather/pull/612#issuecomment-507568217 looks like a Music player 
  image

**Comment by puzzler-1** [comment]
Since I needed a calculator icon, I edited [ahtohbi4](https://github.com/ahtohbi4)'s one to:
```svg
<rect x="3" y="1" width="18" height="22" rx="2" />
<rect x="7" y="5" width="10" height="2"  />
<path d="M8 20V19" />
<path d="M8 16V15" />
<path d="M8 12V11" />
<path d="M12 20V19" />
<path d="M12 16V15" />
<path d="M12 12V11" />
<path d="M16 20V19" />
<path d="M16 16V15" />
<path d="M16 12V11" />
```

calculator
It complies with feather's general style - not complex and nice spacing.

**Comment by locness3** [comment]
You could also use @lucide-icons, we have a calculator icon.

**Pull request closed without merging**
