### PR TITLE
feat: Add `patreon` icon

### LINKED ISSUE #108: Icon Request: Patreon
An icon to represent Patreon, useful on webpages
image

### PR DESCRIPTION
**Pull request by johnletey**
Closes #108

### CODE REVIEW

**Comment by mittalyashu** [comment]
The size of the circle is bigger, according to [Patreon Logo Guidelines](https://www.patreon.com/brand).

image

**Comment by johnletey** [comment]
> The size of the circle is bigger

@mittalyashu So you want me to make the circle bigger?

**Comment by mittalyashu** [comment]
> @mittalyashu So you want me to make the circle bigger?
The opposite. @johnletey

**Comment by johnletey** [comment]
@mittalyashu I see ... it's currently 15px by 15px ... this is what it looks like when I shrink down to 10px by 10px:

Shot 2019-07-26 at 11 46 52

Although I personally think that it's a bit to small ... so here's what it looks like at 11px by 11px:

Shot 2019-07-26 at 11 46 25

**Comment by mittalyashu** [comment]
keeping the circle 11px might be out of position. How about 12px?

**Comment by johnletey** [comment]
So like this @mittalyashu?

Shot 2019-07-27 at 13 09 09

**Comment by mittalyashu** [comment]
Ah! 😍

Much better, it perfectly again with the Grid and makes a perfect shape.

**Comment by johnletey** [comment]
Wonderful @mittalyashu ... I have updated the PR!

**Comment by Truefit-Derek** [comment]
I'm not very Github savvy, but in an app design we're working on I had to create one for Patreon and the attached image is what I came up with FWIW. I feel the single line like the one above (by @johnletey)—while nice—doesn't quite represent their brand IMO. It's a distinct rectangle. Keep in mind I didn't do a whole lot of research before creating the icon—there may be one from Patreon from their brand guidelines documentation. I didn't have time to do much research before creating it for out design.
patreon

**Comment by colebemis** [comment]
Thanks for opening this PR, @johnletey! I'm going to close this because we've decided to stop adding logo icons to Feather (see #763 for more details).

**Pull request closed without merging**
